// Generated by https://quicktype.io

export interface AssetDetail {
  pkAssetHistoryDetailId: number;
  fkAssetId: FkAssetID;
  timeOfTracking: string;
  latitude: number;
  longitude: number;
}

export interface FkAssetID {
  pkAssetId: number;
  fkAssetType: FkAssetType;
  assetName: string;
  assetContactDetail: number;
}

export interface FkAssetType {
  pkAssetTypeId: number;
  assetType: string;
}

export interface AssetHistory {
  timeOfTracking: string;
  latitude: number;
  pkAssetHistoryDetailId: number;
  longitude: number;
}

export interface LuSecurityRole {
  pkSecurityRoleId: number;
  roleName: string;
}
